### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by wheremiah**
I fixed a bug in the README to see how pull requests work.

### CODE REVIEW

**Comment by wheremiah** [comment]
Sooo, I guess I should have made a branch first rather than doing a pull request from dev to master...

**Comment by jessemyers** [comment]
Yeah, I'm not doing git-flow for these repos. I'm also planning to delete
this particular repo because I think I can generalize packer_ubuntu to
build all of the images (I already did that for Vagrant boxes).

**Comment by wheremiah** [comment]
Cool, btw I also hooked fisheye up to github, so we could do reviews of code here if we wanted.

**Comment by vincer** [comment]
Sure, I'm fine with dropping git-flow in these.

@jessemyers, do you mean packer_docker-base or are you planning on pushing a new repo to hold everything?

My only thought is that I think splitting repos where images will depend on each other is nice. openvpn uses the docker-base image as a source AMI. If they're in the same repo then when we make a change to docker-base, we need to commit/release/build that, then update the source AMI for openvpn and commit/release/build the same repo again which will also build a new docker-base image (unless we only manually trigger builds).

**Comment by jessemyers** [comment]
I have a few repos under my personal github from colloquium where I was
playing with Hashicorp's "best practices" and trying to adapt it to our
needs. It's still a work in progress slash spare time project, but I
noticed a few things while going through the exercise:
- Having the repos split apart creates a lot of repetition of repo
  structure. I ended up with one repo for the base ubuntu, one for docker,
  one for openvpn, one for the ansible project structure, and one for the
  packer scripts (plus the bento subtree), not to mention all of the ansible
  roles. I'm pretty sure that all of this can be combined into a single repo
  (minus the bento subtree and ansible roles), which makes the code base a
  lot simpler.
- I decided to try skipping git-flow since it's felt like more of an
  encumbrance than an asset through the last few months of dev-ops'ing. The
  big benefit of git-flow (beyond standardized tooling) is separation of
  release work from development work. But the reality is: we almost never
  have long-lived release branches and almost never test them in isolation in
  any significant way. Larger parts of the world get by with master + PRs so
  I wanted to play with that model. So far I think it fits better with a
  CI/CD promotion process, at least with a small group of skilled developers.
  (I still think git-flow has its place, but maybe not in this domain, with
  this team.)
- I've only been triggering builds manually so far. I haven't thought
  about how best to chain image builds. But my instinct is that we still
  don't get much benefit from separate repos (yet). Suppose the ubuntu or
  docker base images change; if you're using Atlas to inject the dependency
  image, there's nothing in git for openvpn that would change and therefore
  nothing that would automatically trigger a build.

Anyway, you can see my playground project(s) here:
https://github.com/jessemyers/packer_ubuntu

There are also similar projects for docker and openvpn at the moment, but I
plan to delete those. And if that works and time allows, port this
structure back into the llabs images.

**Comment by vincer** [comment]
Good point about Atlas-injected dependencies, hadn't thought about that.

The middleman packer-ansible project is now dead so we just have the roles and a packer repo per image type that use the roles.

I guess it may just come done to aesthetic preference. The separate repos feel a bit more "right" to me, but not a huge deal either way.

**Pull request merged**
